import "./src/styles/global.css";
import "./src/styles/font.css";
import React from "react";
import { ThemeWrapper } from "./root";
export const onRenderBody = ({ setHeadComponents }) => {
  setHeadComponents([
    <link
      key='Poppins'
      rel='preload'
      href='/fonts/Poppins-Black.ttf'
      as='font'
      type='font/tff'
      crossOrigin='anonymous'
    />,
    <link
      key='Poppins'
      rel='preload'
      href='/fonts/Poppins-BlackItalic.ttf'
      as='font'
      type='font/tff'
      crossOrigin='anonymous'
    />,
    <link
      key='Poppins'
      rel='preload'
      href='/fonts/Poppins-Bold.ttf'
      as='font'
      type='font/tff'
      crossOrigin='anonymous'
    />,
    <link
      key='Poppins'
      rel='preload'
      href='/fonts/Poppins-BoldItalic.ttf'
      as='font'
      type='font/tff'
      crossOrigin='anonymous'
    />,
    <link
      key='Poppins'
      rel='preload'
      href='/fonts/Poppins-ExtraBold.ttf'
      as='font'
      type='font/tff'
      crossOrigin='anonymous'
    />,
    <link
      key='Poppins'
      rel='preload'
      href='/fonts/Poppins-ExtraBoldItalic.ttf'
      as='font'
      type='font/tff'
      crossOrigin='anonymous'
    />,
    <link
      key='Poppins'
      rel='preload'
      href='/fonts/Poppins-ExtraLight.ttf'
      as='font'
      type='font/tff'
      crossOrigin='anonymous'
    />,
    <link
      key='Poppins'
      rel='preload'
      href='/fonts/Poppins-ExtraLightItalic.ttf'
      as='font'
      type='font/tff'
      crossOrigin='anonymous'
    />,
    <link
      key='Poppins'
      rel='preload'
      href='/fonts/Poppins-Light.ttf'
      as='font'
      type='font/tff'
      crossOrigin='anonymous'
    />,
    <link
      key='Poppins'
      rel='preload'
      href='/fonts/Poppins-Italic.ttf'
      as='font'
      type='font/tff'
      crossOrigin='anonymous'
    />,

    <link
      key='Poppins'
      rel='preload'
      href='/fonts/Medium-Bold.ttf'
      as='font'
      type='font/tff'
      crossOrigin='anonymous'
    />,
    <link
      key='Poppins'
      rel='preload'
      href='/fonts/Poppins-LightItalic.ttf'
      as='font'
      type='font/tff'
      crossOrigin='anonymous'
    />,

    <link
      key='Poppins'
      rel='preload'
      href='/fonts/Regular-Bold.ttf'
      as='font'
      type='font/tff'
      crossOrigin='anonymous'
    />,
    <link
      key='Poppins'
      rel='preload'
      href='/fonts/Poppins-MediumItalic.ttf'
      as='font'
      type='font/tff'
      crossOrigin='anonymous'
    />,
    <link
      key='Poppins'
      rel='preload'
      href='/fonts/Poppins-SemiBold.ttf'
      as='font'
      type='font/tff'
      crossOrigin='anonymous'
    />,
    <link
      key='Poppins'
      rel='preload'
      href='/fonts/Poppins-SemiBoldItalic.ttf'
      as='font'
      type='font/tff'
      crossOrigin='anonymous'
    />,
    <link
      key='Poppins'
      rel='preload'
      href='/fonts/Poppins-Thin.ttf'
      as='font'
      type='font/tff'
      crossOrigin='anonymous'
    />,
    <link
      key='Poppins'
      rel='preload'
      href='/fonts/Poppins-ThinItalic.ttf'
      as='font'
      type='font/tff'
      crossOrigin='anonymous'
    />,
  ]);
};
export const wrapRootElement = ThemeWrapper;
